/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    products: Product;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'journal-page': JournalPage;
    'storefront-page': StorefrontPage;
    'projects-page': ProjectsPage;
    'journey-page': JourneyPage;
    'tech-stack-page': TechStackPage;
    'certifications-page': CertificationsPage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'journal-page': JournalPageSelect<false> | JournalPageSelect<true>;
    'storefront-page': StorefrontPageSelect<false> | StorefrontPageSelect<true>;
    'projects-page': ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    'journey-page': JourneyPageSelect<false> | JourneyPageSelect<true>;
    'tech-stack-page': TechStackPageSelect<false> | TechStackPageSelect<true>;
    'certifications-page': CertificationsPageSelect<false> | CertificationsPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  category?: ('brand' | 'hero' | 'product' | 'project' | 'post' | 'general') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  category: string;
  featured?: boolean | null;
  excerpt: string;
  coverImage?: (number | null) | Media;
  coverVideo?: string | null;
  body: string;
  publishedAt: string;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  badge?: string | null;
  category?: string | null;
  status?: ('active' | 'growing' | 'validation' | 'future') | null;
  image?: (number | null) | Media;
  imageAlt?: string | null;
  summary: string;
  meta?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  muted?: boolean | null;
  problemSolved?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  badge?: string | null;
  focus?: string | null;
  status?: ('active' | 'growing' | 'focused' | 'future') | null;
  image?: (number | null) | Media;
  imageAlt?: string | null;
  summary: string;
  meta?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  muted?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  featured?: T;
  excerpt?: T;
  coverImage?: T;
  coverVideo?: T;
  body?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  badge?: T;
  category?: T;
  status?: T;
  image?: T;
  imageAlt?: T;
  summary?: T;
  meta?:
    | T
    | {
        value?: T;
        id?: T;
      };
  featured?: T;
  muted?: T;
  problemSolved?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  badge?: T;
  focus?: T;
  status?: T;
  image?: T;
  imageAlt?: T;
  summary?: T;
  meta?:
    | T
    | {
        value?: T;
        id?: T;
      };
  featured?: T;
  muted?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand: {
    brandName: string;
    legalName?: string | null;
    tagline?: string | null;
    logo?: (number | null) | Media;
  };
  business?: {
    siteUrl?: string | null;
    supportEmail?: string | null;
    primaryLocation?: string | null;
  };
  primaryNavigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  headerAction: {
    label: string;
    href: string;
  };
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerMeta?: {
    headline?: string | null;
    description?: string | null;
    copyrightText?: string | null;
  };
  seoDefaults?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    description: string;
    image?: (number | null) | Media;
    imageAlt?: string | null;
    actions?:
      | {
          label: string;
          href: string;
          variant?: ('primary' | 'secondary') | null;
          id?: string | null;
        }[]
      | null;
    points?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    metrics?:
      | {
          badge?: string | null;
          title: string;
          description: string;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          meta?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
          featured?: boolean | null;
          muted?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  positioning: {
    eyebrow?: string | null;
    title: string;
    description: string;
  };
  structure: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    items?:
      | {
          badge?: string | null;
          title: string;
          description: string;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          meta?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
          featured?: boolean | null;
          muted?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  storefrontSection: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    items?: (number | Product)[] | null;
  };
  buildSection: {
    eyebrow?: string | null;
    title: string;
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  businessModel: {
    eyebrow?: string | null;
    title: string;
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  execution: {
    eyebrow?: string | null;
    title: string;
    link: {
      label: string;
      href: string;
    };
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  lens: {
    eyebrow?: string | null;
    title: string;
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  growthHub: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    items?:
      | {
          title: string;
          description: string;
          href: string;
          linkLabel: string;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  focus: {
    eyebrow?: string | null;
    title: string;
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  lead: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    buttonLabel?: string | null;
    successMessage?: string | null;
    note?: string | null;
  };
  contactCTA: {
    eyebrow?: string | null;
    title: string;
    description: string;
    label: string;
    href: string;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    description: string;
    image?: (number | null) | Media;
    imageAlt?: string | null;
  };
  identity: {
    eyebrow?: string | null;
    title: string;
    description: string;
  };
  values?: {
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  structure: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    items?:
      | {
          badge?: string | null;
          title: string;
          description: string;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          meta?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
          featured?: boolean | null;
          muted?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    eyebrow?: string | null;
    title: string;
    description: string;
    label: string;
    href: string;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page".
 */
export interface JournalPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    description: string;
    image?: (number | null) | Media;
    imageAlt?: string | null;
  };
  editorial: {
    eyebrow?: string | null;
    title: string;
    description: string;
  };
  featured: {
    eyebrow?: string | null;
    title: string;
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    eyebrow?: string | null;
    title: string;
    description: string;
    label: string;
    href: string;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storefront-page".
 */
export interface StorefrontPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    description: string;
    image?: (number | null) | Media;
    imageAlt?: string | null;
  };
  productsSection: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    items?: (number | Product)[] | null;
  };
  summary?: {
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  lead: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    buttonLabel?: string | null;
    successMessage?: string | null;
    note?: string | null;
  };
  cta: {
    eyebrow?: string | null;
    title: string;
    description: string;
    label: string;
    href: string;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page".
 */
export interface ProjectsPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    description: string;
    image?: (number | null) | Media;
    imageAlt?: string | null;
  };
  pipeline: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    items?: (number | Project)[] | null;
  };
  summary?: {
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    eyebrow?: string | null;
    title: string;
    description: string;
    label: string;
    href: string;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-page".
 */
export interface JourneyPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    description: string;
    image?: (number | null) | Media;
    imageAlt?: string | null;
  };
  focus: {
    eyebrow?: string | null;
    title: string;
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  documentation: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  future: {
    eyebrow?: string | null;
    title: string;
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    eyebrow?: string | null;
    title: string;
    description: string;
    label: string;
    href: string;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-stack-page".
 */
export interface TechStackPage {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    description: string;
    image?: (number | null) | Media;
    imageAlt?: string | null;
  };
  primary: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    items?:
      | {
          title: string;
          label?: string | null;
          logo?: string | null;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  secondary: {
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    items?:
      | {
          title: string;
          label?: string | null;
          logo?: string | null;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  support: {
    eyebrow?: string | null;
    title: string;
    items?:
      | {
          title: string;
          description: string;
          status?: string | null;
          image?: (number | null) | Media;
          imageAlt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    eyebrow?: string | null;
    title: string;
    description: string;
    label: string;
    href: string;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications-page".
 */
export interface CertificationsPage {
  id: number;
  /**
   * Transitional JSON storage for the current certifications page while the richer field model is being built.
   */
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  /**
   * Transitional JSON storage for the current contact page while richer admin-specific fields are being broken out.
   */
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        brandName?: T;
        legalName?: T;
        tagline?: T;
        logo?: T;
      };
  business?:
    | T
    | {
        siteUrl?: T;
        supportEmail?: T;
        primaryLocation?: T;
      };
  primaryNavigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerAction?:
    | T
    | {
        label?: T;
        href?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerMeta?:
    | T
    | {
        headline?: T;
        description?: T;
        copyrightText?: T;
      };
  seoDefaults?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
        actions?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              id?: T;
            };
        points?:
          | T
          | {
              value?: T;
              id?: T;
            };
        metrics?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
              image?: T;
              imageAlt?: T;
              meta?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              featured?: T;
              muted?: T;
              id?: T;
            };
      };
  positioning?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  structure?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
              image?: T;
              imageAlt?: T;
              meta?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              featured?: T;
              muted?: T;
              id?: T;
            };
      };
  storefrontSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?: T;
      };
  buildSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  businessModel?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  execution?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  lens?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  growthHub?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              href?: T;
              linkLabel?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  focus?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  lead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        buttonLabel?: T;
        successMessage?: T;
        note?: T;
      };
  contactCTA?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        label?: T;
        href?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
      };
  identity?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  values?:
    | T
    | {
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  structure?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
              image?: T;
              imageAlt?: T;
              meta?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              featured?: T;
              muted?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        label?: T;
        href?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page_select".
 */
export interface JournalPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
      };
  editorial?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  featured?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        label?: T;
        href?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storefront-page_select".
 */
export interface StorefrontPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
      };
  productsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?: T;
      };
  summary?:
    | T
    | {
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  lead?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        buttonLabel?: T;
        successMessage?: T;
        note?: T;
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        label?: T;
        href?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
      };
  pipeline?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?: T;
      };
  summary?:
    | T
    | {
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        label?: T;
        href?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journey-page_select".
 */
export interface JourneyPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
      };
  focus?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  documentation?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  future?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        label?: T;
        href?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-stack-page_select".
 */
export interface TechStackPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        image?: T;
        imageAlt?: T;
      };
  primary?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              label?: T;
              logo?: T;
              description?: T;
              id?: T;
            };
      };
  secondary?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              label?: T;
              logo?: T;
              description?: T;
              id?: T;
            };
      };
  support?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              status?: T;
              image?: T;
              imageAlt?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        label?: T;
        href?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications-page_select".
 */
export interface CertificationsPageSelect<T extends boolean = true> {
  content?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  content?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}